~setvalue^Ajax~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~expand^edit^index-ajax.inc^Index Ajax~
~expand^edit^control-ajax.inc^Control Ajax~
~expand^edit^battery-ajax.inc^Battery Ajax~
~expand^edit^manage-ajax.inc^Manage Ajax~
~expand^edit^tank-ajax.inc^Tank Ajax~
~expand^edit^backup-ajax.inc^Backup Ajax~
~expand^edit^plot-ajax.inc^Plot Ajax~
~expand^edit^rest-ajax.inc^Rest Ajax~
~expand^edit^fresh-ajax.inc^Fresh Ajax~
~expand^edit^lpg-ajax.inc^Lpg Ajax~
~expand^edit^heater-ajax.inc^Heater Ajax~
~expand^edit^aging-ajax.inc^Aging Ajax~
~expand^edit^can-ajax.inc^Aging Ajax~
</body>
</html>
