~setvalue^Ajax~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~zerocount~
~expand^anchor^Index~
~expand^anchor^Control~
~expand^anchor^Battery~
~expand^anchor^Manage~
~expand^anchor^Tank~
~expand^anchor^Backup~
~expand^anchor^Plot~
~expand^anchor^Rest~
~expand^anchor^Fresh~
~expand^anchor^Lpg~
~expand^anchor^Heater~
~expand^anchor^Aging~
~expand^anchor^Charge~
~expand^anchor^Can~
~zerocount~
~expand^edit^index-ajax.inc^Index~
~expand^edit^control-ajax.inc^Control~
~expand^edit^battery-ajax.inc^Battery~
~expand^edit^manage-ajax.inc^Manage~
~expand^edit^tank-ajax.inc^Tank~
~expand^edit^backup-ajax.inc^Backup~
~expand^edit^plot-ajax.inc^Plot~
~expand^edit^rest-ajax.inc^Rest~
~expand^edit^fresh-ajax.inc^Fresh~
~expand^edit^lpg-ajax.inc^Lpg~
~expand^edit^heater-ajax.inc^Heater~
~expand^edit^aging-ajax.inc^Aging~
~expand^edit^charge-ajax.inc^Charge~
~expand^edit^can-ajax.inc^Can~
</body>
</html>
