~setvalue^Control~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <script src='/ajax.js' type='text/javascript'></script>
   <script src='/control.js' type='text/javascript'></script>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
<br/>
~expand^switch^Water pump^att-control-water-pump~
<br/>
~expand^switch^Water fill^att-control-water-fill~
<br/>
~expand^switch^Water drain^att-control-water-drain~
<br/>
~expand^switch^Inverter^att-control-inverter~
<br/>
~expand^switch^Lpg heater^att-control-lpg-heater~
<br/>
~expand^led^D+^att-control-dplus~
~expand^led^EHU^att-control-ehu~
<br/>
~expand^value^Litres^txt-control-litres^3.0~
~expand^input^Min litres for pump^val-control-pump-min-litres^3.0~
~expand^input^Min litres for pump with D+^val-control-pump-dplus-litres^3.0~
~expand^input^Max litres for drain^val-control-drain-max-litres^3.0~
</body>
</html>