~setvalue^Data~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~zerocount~
~expand^anchor^Charge~
~expand^anchor^Heater~
~expand^anchor^Aging~
~expand^anchor^Lpg~
~expand^anchor^Fresh~
~expand^anchor^Plot~
~zerocount~
~expand^edit^../data/charge^Charge~
~expand^edit^../data/heater^Heater~
~expand^edit^../data/aging^Aging~
~expand^edit^../data/lpg^Lpg~
~expand^edit^../data/fresh^Fresh~
~expand^edit^../data/plot^Plot~
</body>
</html>