~setvalue^HTML~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~expand^edit^login.inc^Login~
~expand^edit^index.inc^Index~
~expand^edit^control.inc^Control~
~expand^edit^battery.inc^Battery~
~expand^edit^manage.inc^Manage~
~expand^edit^tank.inc^Tank~
~expand^edit^backup.inc^Backup~
~expand^edit^config.inc^Config~
~expand^edit^data.inc^Data~
~expand^edit^log.inc^Log~
~expand^edit^system.inc^System~
~expand^edit^html.inc^HTML~
~expand^edit^include.inc^Include~
~expand^edit^ajax.inc^Ajax~
~expand^edit^js.inc^JS~
~expand^edit^css.inc^CSS~
</body>
</html>
