~setvalue^Include~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~zerocount~
~expand^anchor^Menu~
~expand^anchor^Anchor~
~expand^anchor^Edit~
~expand^anchor^Input~
~expand^anchor^Value~
~expand^anchor^Switch~
~expand^anchor^Led~
~expand^anchor^Button~
~expand^anchor^Meter~
~zerocount~
~expand^edit^menu.inc^Menu~
~expand^edit^anchor.inc^Anchor~
~expand^edit^edit.inc^Edit~
~expand^edit^input.inc^Input~
~expand^edit^value.inc^Value~
~expand^edit^switch.inc^Switch~
~expand^edit^led.inc^Led~
~expand^edit^button.inc^Button~
~expand^edit^meter.inc^Meter~
</body>
</html>