~setvalue^JS~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~expand^anchor^Index~
~expand^anchor^Control~
~expand^anchor^Battery~
~expand^anchor^Manage~
~expand^anchor^Tank~
~expand^anchor^Backup~
~expand^anchor^Ajax~
~expand^edit^index.js^Index~
~expand^edit^control.js^Control~
~expand^edit^battery.js^Battery~
~expand^edit^manage.js^Manage~
~expand^edit^tank.js^Tank~
~expand^edit^backup.js^Backup~
~expand^edit^ajax.js^Ajax~
</body>
</html>