<style type='text/css'>
	nav ul li#~getvalue~    { background:coral; }
</style>
<nav><ul>
<li id='Home'><a href='/'>Home</a></li>
<li id='Control'><a href='/control'>Control</a></li>
<li id='Manage'><a href='/manage'>Manage</a></li>
<li id='Battery'><a href='/battery'>Battery</a></li>
<li id='Tank'><a href='/tank'>Tank</a></li>
<li id='Backup'><a href='/backup'>Backup</a></li>
<li id='Config'><a href='/config'>Config</a></li>
<li id='Data'><a href='/data'>Data</a></li>
<li id='Log'><a href='/log'>Log</a></li>
<li id='System'><a href='/system'>System</a></li>
<li id='HTML'><a href='/html'>HTML</a></li>
<li id='Include'><a href='/include'>Include</a></li>
<li id='Ajax'><a href='/ajax'>Ajax</a></li>
<li id='JS'><a href='/js'>JS</a></li>
<li id='CSS'><a href='/css'>CSS</a></li>
</ul></nav>