~setvalue^System~
<!DOCTYPE html>
<html>
<head>
   <title>Motorhome - ~getvalue~</title>
   <link rel='stylesheet' href='/base.css' type='text/css'/>
   <link rel='stylesheet' href='/settings.css' type='text/css'/>
   <meta name='viewport' content='width=device-width, initial-scale=1'>
   <link rel='icon'       href='/favicon.ico' type='image/x-icon'/>
</head>
<body>
<a class='tab-shortcut' href='#main-content'>Skip to content</a>
~expand^menu~
<h1 id='main-content'>Motorhome - ~getvalue~</h1>
~zerocount~
~expand^anchor^Todo~
~expand^anchor^Wires~
~expand^anchor^Setup information~
~expand^anchor^Service~
~expand^anchor^Core dumps systemd~
~expand^anchor^Core dumps general~
~expand^anchor^sysctl.conf~
~expand^anchor^Startup~
~expand^anchor^crontab~
~expand^anchor^fstab~
~expand^anchor^interfaces~
~expand^anchor^boot/config.txt~
~zerocount~
~expand^edit^../todo.txt^Todo~
~expand^edit^../wires.txt^Wires~
~expand^edit^../setup.txt^Setup information~
~expand^edit^/etc/systemd/system/server.service^Service~
~expand^edit^/etc/sysctl.d/core.conf^Core dumps systemd~
~expand^edit^/etc/security/limits.conf^Core dumps general~
~expand^edit^/etc/sysctl.conf^sysctl.conf~
~expand^edit^/etc/rc.local^Startup~
~expand^edit^/etc/crontab^crontab~
~expand^edit^/etc/fstab^fstab~
~expand^edit^/etc/network/interfaces^interfaces~
~expand^edit^/boot/config.txt^boot/config.txt~
</body>
</html>
