#include <stdint.h>
extern uint32_t CanThisGetBatteryCountedCapacityAs      (void);
extern int32_t  CanThisGetBatteryCurrentMa              (void);
extern uint8_t  CanThisGetBatteryCapacityTargetPercent  (void);
extern char     CanThisGetBatteryOutputState            (void);
extern char     CanThisGetBatteryChargeEnabled          (void);
extern char     CanThisGetBatteryDischargeEnabled       (void);
extern int16_t  CanThisGetBatteryTemperature8bfdp       (void);
extern int16_t  CanThisGetBatteryTemperatureTargetTenths(void);
extern uint8_t  CanThisGetBatteryHeaterOutput8bfdp      (void);
extern uint8_t  CanThisGetBatteryHeaterProportional     (void);
extern uint8_t  CanThisGetBatteryHeaterIntegral         (void);
extern int16_t  CanThisGetBatteryVoltageMv              (void);
extern int16_t  CanThisGetBatteryAgingAsPerHour         (void);

extern int16_t  CanThisGetTankFreshTemperature          (void);
extern uint64_t CanThisGetTankFreshRom                  (void);
extern int16_t  CanThisGetTankFreshSupplyMv             (void);
extern int16_t  CanThisGetTankFreshBaseTemp16ths        (void);
extern int16_t  CanThisGetTankFreshBaseMv               (void);
extern int16_t  CanThisGetTankFreshUvPer16th            (void);
extern int16_t  CanThisGetTankFreshMv                   (void);
extern int16_t  CanThisGetTankFreshDepthMm              (void);
extern int16_t  CanThisGetTankFreshLitres               (void);
extern int16_t  CanThisGetTankSensorPosnFront           (void);
extern int16_t  CanThisGetTankSensorPosnRight           (void);
extern uint16_t CanThisGetTankWidth                     (void);
extern uint16_t CanThisGetTankLength                    (void);
extern int16_t  CanThisGetTankAccelerometerXFlat        (void);
extern int16_t  CanThisGetTankAccelerometerYFlat        (void);
extern int16_t  CanThisGetTankAccelerometerZFlat        (void);
extern int16_t  CanThisGetTankAccelerometerX            (void);
extern int16_t  CanThisGetTankAccelerometerY            (void);
extern int16_t  CanThisGetTankAccelerometerZ            (void);
extern uint64_t CanThisGetTankRom0                      (void);
extern uint64_t CanThisGetTankRom1                      (void);
extern uint64_t CanThisGetTankRom2                      (void);
extern uint64_t CanThisGetTankRom3                      (void);
extern int16_t  CanThisGetTankRomData0                  (void);
extern int16_t  CanThisGetTankRomData1                  (void);
extern int16_t  CanThisGetTankRomData2                  (void);
extern int16_t  CanThisGetTankRomData3                  (void);
extern int16_t  CanThisGetTankLpgMv                     (void);
extern int16_t  CanThisGetTankLpgResistance16ths        (void);
extern int16_t  CanThisGetTankLpgResistanceMin16ths     (void);
extern int16_t  CanThisGetTankLpgResistanceMax16ths     (void);
extern int16_t  CanThisGetTankLpgVolumeMinMl            (void);
extern int16_t  CanThisGetTankLpgVolumeMaxMl            (void);
extern int16_t  CanThisGetTankLpgVolumeMl               (void);
extern uint64_t CanThisGetAmbientOutsideRom             (void);
extern uint64_t CanThisGetAmbientHeatingRom             (void);
extern int16_t  CanThisGetAmbientOutsideTemp16ths       (void);
extern int16_t  CanThisGetAmbientHeatingTemp16ths       (void);

extern char     CanThisGetControlWaterPump              (void);
extern char     CanThisGetControlWaterFill              (void);
extern char     CanThisGetControlWaterDrain             (void);
extern char     CanThisGetControlInverter               (void);
extern char     CanThisGetControlDPlus                  (void);
extern int16_t  CanThisGetControlPumpMinLitres          (void);
extern int16_t  CanThisGetControlPumpDplusLitres        (void);
extern int16_t  CanThisGetControlDrainMaxLitres         (void);

extern void CanThisSendServerTime                   (uint32_t value);

extern void CanThisSetBatteryCountedCapacityAs      (uint32_t value);
//extern void CanThisSetBatteryCurrentMa              (int32_t  value);
extern void CanThisSetBatteryCapacityTargetPercent  (uint8_t  value);
//extern void CanThisSetBatteryOutputState            (char     value);
extern void CanThisSetBatteryChargeEnabled          (char     value);
extern void CanThisSetBatteryDischargeEnabled       (char     value);
extern void CanThisSetBatteryTemperatureTargetTenths(int16_t  value);
extern void CanThisSetBatteryHeaterProportional     (uint16_t value);
extern void CanThisSetBatteryHeaterIntegral         (uint16_t value);
extern void CanThisSetBatteryAgingAsPerHour         (int16_t  value);
extern void CanThisSetTankFreshBaseTemp16ths        (int16_t  value);
extern void CanThisSetTankFreshBaseMv               (int16_t  value);
extern void CanThisSetTankFreshUvPer16th            (int16_t  value);
extern void CanThisSetTankSensorPosnFront           (int16_t  value);
extern void CanThisSetTankSensorPosnRight           (int16_t  value);
extern void CanThisSetTankWidth                     (uint16_t value);
extern void CanThisSetTankLength                    (uint16_t value);
extern void CanThisSetTankAccelerometerXFlat        (int16_t  value);
extern void CanThisSetTankAccelerometerYFlat        (int16_t  value);
extern void CanThisSetTankAccelerometerZFlat        (int16_t  value);
extern void CanThisSetTankFreshRom                  (uint64_t value);
extern void CanThisSetTankLpgResistanceMin16ths     (int16_t  value);
extern void CanThisSetTankLpgResistanceMax16ths     (int16_t  value);
extern void CanThisSetTankLpgVolumeMinMl            (int16_t  value);
extern void CanThisSetTankLpgVolumeMaxMl            (int16_t  value);
extern void CanThisSetAmbientOutsideRom             (uint64_t value);
extern void CanThisSetAmbientHeatingRom             (uint64_t value);
extern void CanThisSetControlWaterPump              (char     value);
extern void CanThisSetControlWaterFill              (char     value);
extern void CanThisSetControlWaterDrain             (char     value);
extern void CanThisSetControlInverter               (char     value);
extern void CanThisSetControlPumpMinLitres          (int16_t  value);
extern void CanThisSetControlPumpDplusLitres        (int16_t  value);
extern void CanThisSetControlDrainMaxLitres         (int16_t  value);

extern void CanThisReceive();
extern void CanThisInit();
